### ISSUE TITLE
app.use documentation

### ISSUE THREAD

**Issue by pfraces** [senchalabs/connect#1060]
Where is placed the documentation about the `use()` method currently?

I didn't find it neither in the readme nor in the wiki, and the link in the repo description redirects to the readme

I have had to see the code to make sure it keeps allowing a route as first argument, but didn't know if
it allows wildcards such as `:id` and `:id?`

**Comment by Floriferous** [comment]
Is there a middleware or extension/plugin that adds this feature to this package?
