### ISSUE TITLE
Connect Documentation Redirects (But Shouldn't?)

### ISSUE THREAD

**Issue by alanjames1987** [senchalabs/connect#1061]
The connect website (http://www.senchalabs.org/connect) shows for just a second before redirecting to the GitHub page.

This is from this line...

``` html
<meta http-equiv="refresh" content="0;URL=https://github.com/senchalabs/connect#readme">
```

...inside `index.html` file in the `gp-pages` branch.

I know this was intentional added on July 20th but I'm wondering if it should still be there.

**Comment by dougwilson** [comment]
Docs are being added directly to the README now.
