### ISSUE TITLE
Simple but not documented: How do you send a file?

### ISSUE THREAD

**Issue by binarykitchen** [senchalabs/connect#1070]
Been searching everywhere and haven't found a clue yet.

Tell me, how do you send a single local file with one of these code middleware? I mean, I run a small gulp-connect server here and, depending on the URL, I want to send a specific HTML file. How do I implement this?

Thanks!

**Comment by dougwilson** [comment]
`connect` itself has no such way; sending anything just using Node.js core functionality (this is in contrast to `express`, which adds convenience methods like `res.sendFile`).

The most basic Node.js core way to send a single file from the file system is seen here: https://github.com/jshttp/on-finished#example

```js
var connect = require('connect')
var destroy = require('destroy')
var fs = require('fs')
var onFinished = require('on-finished')

var app = connect()

app.use(function (req, res, next) {
  if (req.url != '/' || req.method !== 'GET') {
    return next()
  }

  var stream = fs.createReadStream('index.html')
  stream.pipe(res)
  onFinished(res, function (err) {
    destroy(stream)
  })
})
```

**Comment by binarykitchen** [comment]
thanks for the example
