### ISSUE TITLE
Partial reads on requests lock up proxy

### ISSUE THREAD

**Issue by RealNitro** [senchalabs/connect#1071]
When GET requests are not fully 'read', a connect proxy will never close the connection to the proxied server, even when the TCP connection on the client side has disappeared.

1. Put all files from gist https://gist.github.com/RealNitro/13edd137cd2b3f98dec9 in a folder (bash required)
2. Run npm install
3. Run npm start
4. In a different terminal run ./proxy-blocker.sh
5. After about 5 GETs, the script hangs because the proxy server hangs

Expected: the proxy server closes the connection to the backend server when it notices the connection to the client has been closed.

**Comment by dougwilson** [comment]
Hi @RealNitro ! Do you know if this is a bug in `connect` and not in the `proxy-middleware` module? @andrewrk can you take a look at this in your module to confirm/deny?

**Comment by andrewrk** [comment]
I'm running an "experiment" with proxy-middleware where I don't really think about the code and I basically merge every pull request that comes in as long as it has tests. So far it hasn't been very successful and it's resulted in poor quality code. It's probably a bug in proxy-middleware.

**Comment by dougwilson** [comment]
Hi @RealNitro it looks like this may be your issue: https://github.com/andrewrk/connect-proxy/issues/25 If not, please feel free to open a new issue over at https://github.com/andrewrk/connect-proxy/issues :)
