### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by AsherBarak** [senchalabs/connect#1074]
Is it possible that a library so popular has no type script typing?
Did I just miss it searching?

**Comment by dougwilson** [comment]
I'm not sure. What is "type script typing?"

**Comment by AsherBarak** [comment]
http://www.typescriptlang.org/
Gaining a lot of traction now that Angular2 are using them.

**Comment by dougwilson** [comment]
Ah, cool. I just looked at it and didn't see anything immediately saying how to make this bindings or whatever. I can look into learning it, but don't promise anything. If there is a PR you can make, that would of course help a lot as well :)

**Comment by AsherBarak** [comment]
Let me check and get back to you

**Comment by dougwilson** [comment]
Closing this from lack of activity. If you have something, please let me know!
