### ISSUE TITLE
Some of the older versions are still patching cookie routines.

### ISSUE THREAD

**Issue by richtera** [senchalabs/connect#1076]
In order to get around connect-mongodb patching due to an older version of connect as a subdependency I had to put a weird hack in place (added it to the main app.js):
```javascript
var http = require('http');
// Prevent outdated connect patch.
http.OutgoingMessage.prototype._hasConnectPatch = true;
```
The app internally depends on the new version of connect which no longer does this patch, but any other module which still depends on an older version will create a cookie patch which causes a "mess of cookies" to be sent to the browser.

**Comment by dougwilson** [comment]
Ok. I'm not sure what the ask is here? We removes it, and bumped the major version to 3 to correlate. We cannot change 2 behavior, because that is breaking, which is what a major version bump means.

**Comment by richtera** [comment]
I was thinking the new connect could set the property to prevent an old version loaded later from patching
Andy

**Comment by dougwilson** [comment]
Sure, but then people using the old will be broken, as it will be expecting the patches like the headers event to be there.

**Comment by richtera** [comment]
I don’t think so, because this patch along with the new express causes the problem. The patch tries to special case cookies to be made into arrays of set-cookie headers, but the next express already does this internally.

Here is the patch:
```javascript
/*!
 * Connect
 * Copyright(c) 2011 TJ Holowaychuk
 * MIT Licensed
 */

/**
 * Module dependencies.
 */

var http = require('http')
  , res = http.OutgoingMessage.prototype;

// original setHeader()

var setHeader = res.setHeader;

// original _renderHeaders()

var _renderHeaders = res._renderHeaders;

if (res._hasConnectPatch) return;

/**
 * Provide a public "header sent" flag
 * until node does.
 *
 * @return {Boolean}
 * @api public
 */

res.__defineGetter__('headerSent', function(){
  return this._headerSent;
});

/**
 * Set header `field` to `val`, special-casing
 * the `Set-Cookie` field for multiple support.
 *
 * @param {String} field
 * @param {String} val
 * @api public
 */

res.setHeader = function(field, val){
  var key = field.toLowerCase()
    , prev;

  // special-case Set-Cookie
  if (this._headers && 'set-cookie' == key) {
    if (prev = this.getHeader(field)) {
      val = Array.isArray(prev)
        ? prev.concat(val)
        : [prev, val];
    }
  // charset
  } else if ('content-type' == key && this.charset) {
    val += '; charset=' + this.charset;
  }

  return setHeader.call(this, field, val);
};

/**
 * Proxy `res.end()` to expose a 'header' event,
 * allowing arbitrary augmentation before the header
 * fields are written to the socket.
 *
 * NOTE: this _only_ supports node's progressive header
 * field API aka `res.setHeader()`.
 */

res._renderHeaders = function(){
  this.emit('header');
  return _renderHeaders.call(this);
};

res._hasConnectPatch = true;
```

**Comment by richtera** [comment]
Oh I see....
This should probably be set inside of the new version of express :).
