### ISSUE TITLE
How can I find out what anonymous function it is?

### ISSUE THREAD

**Issue by binarykitchen** [senchalabs/connect#1079]
In relation to the issue raised at https://github.com/pillarjs/router/issues/40, I think the problem is that a weird middleware is being used instead of the one I want.

When running in debug mode, `connect:dispatcher anonymous  : /contact +14s` is shown (line 165 in proto.js)

It is anonymous. I would like to see the function. What it is. Where it comes from. So that I can investigate deeper. How can I do that?

**Comment by dougwilson** [comment]
Unfortunately the debugging messages are just for simplistic debugging, and if some code has not named the function that has been attached, then there isn't much to add to the message. You should be able to set a break point in your debugger at https://github.com/senchalabs/connect/blob/master/index.js#L230 to see what `handle` is pointing to.

**Comment by binarykitchen** [comment]
@dougwilson right, the debugger is the answer. But tell me, how can I name a function (middleware) here?

**Comment by dougwilson** [comment]
Hi @binarykitchen, the name of the middleware is simply the name of the function (since a middleware is a function. For example, this middleware would be named "fooMiddleware":
```js
app.use(function fooMiddleware(req, res, next) {
  next()
})
```

I hope that helps!

**Comment by binarykitchen** [comment]
@dougwilson oh, neat, i didn't know that naming anonymous functions directly will do the trick - thanks man
