### ISSUE TITLE
Incoming headers are lowercase, automatic outgoing headers are titlecase

### ISSUE THREAD

**Issue by krainboltgreene** [senchalabs/connect#1081]
I realize that IncomingMessage is the big pain here, since it does the lowercasing, but maybe connect should automatically titlecase outgoing headers?

**Comment by dougwilson** [comment]
If you take a look at the source code, you'll find connect does nothing except provide the foundation for middleware. There is no code related to writing headers or anything. All of that functionality is based on the HTTP server implementation you are using with connect.

**Comment by krainboltgreene** [comment]
All I'm using is Connect :(

On Sat, Apr 2, 2016 at 12:56 PM, Douglas Wilson <notifications@github.com>
wrote:

> Closed #1081 <https://github.com/senchalabs/connect/issues/1081>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/senchalabs/connect/issues/1081#event-612337987>
>



-- 
Kurtis Rainbolt-Greene, Software Developer
Founder of Difference Engineers

2985 San Marino St.
Los Angeles, CA 90006
202-643-2263

**Comment by dougwilson** [comment]
Not sure, then. Would you be able to make a pull request, implementing the behavior you are looking for? Perhaps I'll be able to better understand the request, because connect is only one file and not very many line of code, and certainly none that do with headers.

**Comment by krainboltgreene** [comment]
Definitely, I will! I appreciate the answer :)

**Comment by krainboltgreene** [comment]
Ugh, it looks like it's behavior defined in ServerResponse -.-
