### ISSUE TITLE
Path traversal vulnerability?

### ISSUE THREAD

**Issue by MarkSummers** [senchalabs/connect#1082]
See https://github.com/lud2k/grunt-serve/issues/11

Not sure where exactly the responsibility for guarding against this type of attack should lie, but if I understand correctly then the current situation requires every dependent project to implement the same security checks.

**Comment by dougwilson** [comment]
Hi @MarkSummers, I don't think it lies in this module. You can see our entire source code is just a single file: https://github.com/senchalabs/connect/blob/master/index.js

No where in this file do we ever read from the file system, only route between handlers. The module you linked to, `grunt-serve`, doesn't even use this module anyway; it does require it at https://github.com/lud2k/grunt-serve/blob/master/tasks/serve.js#L12 but it never actually makes any use of this module in it's source code.

**Comment by MarkSummers** [comment]
Agreed.  Thanks for looking into it.
