### ISSUE TITLE
app.use('*.go', function(){})

### ISSUE THREAD

**Issue by gertcuykens** [senchalabs/connect#1086]
Is it possible to implement a glob route?

`app.use('*.go', function(){})`

https://github.com/tapio/live-server/issues/128

**Comment by dougwilson** [comment]
At that point, you probably want to start using the "router" module on top of connect or just express directly.

**Comment by gertcuykens** [comment]
Ok thanks closing this, if you have time please reference a route solution on the [issue](https://github.com/tapio/live-server/issues/128)

**Comment by dougwilson** [comment]
I did read that issue, but I don't understand enough about that module to understand what I can add to the issue.

**Comment by gertcuykens** [comment]
Basicly the proxy url's get dumped into connect [here](https://github.com/tapio/live-server/blob/master/index.js#L198-L205)

Don't understand how I can fit a router in between sorry, a express or browser-sync solution are to heavy for just a developer debug tool.

**Comment by dougwilson** [comment]
Ah, I think I understand your question. That would probably be something the module author would need to do, if they desire to support that type of path. I'm on a phone, so hard to read code on here.

All I can really do is answer your question in the context of this module, which is that this module is a simple scaffolding for making apps using middleware. Complex routing is something you would build on top of connect, and I also publish a module on npm called "router" that does just that.

If you wanted to only use connect to do that type of path matching, just app.use without a path, then in your middleware check the req.url and call next() if the pathname does not end with ".go"

**Comment by gertcuykens** [comment]
Ok `req.url` is something I can work with I think :) So now I need to convince the [proxy-middleware] (https://github.com/andrewrk/node-proxy-middleware) guy first.
