### ISSUE TITLE
app.use('/', () => { }); always hits

### ISSUE THREAD

**Issue by Marvin-Brouwer** [senchalabs/connect#1095]
I'm playing around with this library and I've noticed that if it always gets hit if I configure middleware for the "/" route.
I'd expect every other route to ignore this middleware.

For example if I navigate to "http://127.0.0.1:3000/" I'd expect to see my middleware work.
But if I navigate to "http://127.0.0.1:3000/site.css" I want it to return a "Could not get /site.css" response because I havn't configured error pages yet.

**Comment by dougwilson** [comment]
Hi @Marvin-Brouwer thanks for trying this out! I'm not sure why you would expect it to work that way. Here is the docs from https://github.com/senchalabs/connect#appuseroute-fn :

 > The function will be invoked for every request in which the URL (req.url property) starts with the given route string in the order that app.use is called.

The route string you gave is `/` and both of those start with `/`. Any suggestions for improving the docs?

**Comment by Marvin-Brouwer** [comment]
Aha, I guess I just read past that.
Thanks for your quick reply
