### ISSUE TITLE
app.use chaining

### ISSUE THREAD

**Issue by Islomkhodja** [senchalabs/connect#1098]
> I apologize in advance for my English

Hi! I'm a junior js developer. Last week I started to debug the code and learn how the express and connect works. I really like this, I almost understood, but there are a few questions.

Why in function `proto.use` in the end return `this`. I know that it's used for chaining. But in which cases is it used. Can you give examples?

**Comment by dougwilson** [comment]
For example you can make a oneliner:

    node -e 'require("connect")().use((req, res) => res.end("hello!")).listen(80)'

Returning this means I can declare a full app without assigning values to variables.

I hope this helps!

**Comment by Islomkhodja** [comment]
Nice! Thank you!
