### ISSUE TITLE
Middleware are added as a "stack"?They are added as a "queue".

### ISSUE THREAD

**Issue by onedaywen** [senchalabs/connect#1104]
I have found in [README.md](https://github.com/senchalabs/connect/blob/master/README.md)
### Use middleware
The core of Connect is "using" middleware. Middleware are added as a "stack"
where incoming requests will execute each middleware one-by-one until a middleware
does not call `next()` within it.

```js
app.use(function middleware1(req, res, next) {
  // middleware 1
  next();
});
app.use(function middleware2(req, res, next) {
  // middleware 2
  next();
});
```
but actual the  middleware 1 will be executed first,then executed middleware 2. So Middleware are added as a "queue",First In, First Out.

**Comment by dougwilson** [comment]
The word "stack" is just a generic English word; it is not referring to the computing concept known as a stack.
