### ISSUE TITLE
Stack is not a stack

### ISSUE THREAD

**Issue by riatzukiza** [senchalabs/connect#1105]
If the stack on the `app` were a stack, from the following code you would expect the page to display "foo", but instead it will display "not foo".

```js
app.use("/foo",(req,res) => res.end("not foo"));
app.use("/foo",(req,res) => res.end("foo"));
```

The data structure in use is a queue, if stack is the desired behavior, the index would start at the end of the array and move to the front.

**Comment by dougwilson** [comment]
Hi @riatzukiza ! The word "stack" is just a generic English word; it is not referring to the computing concept known as a stack.

stack (noun): a pile of objects, typically one that is neatly arranged.

**Comment by riatzukiza** [comment]
It would definitely suck to fix this, and run around change all the docs to say the correct word. Then in the process, every article written about the express stack would become inconsistent with the documentation.

**Comment by dougwilson** [comment]
The array is also exposed as the property named "stack" so that should change to reflect the new wording and release a new major version as well.

**Comment by dougwilson** [comment]
As far as I know it has been called "stack" since 2010 and in those 8 years there never seemed to be confusion, especially when the same sentence explains the order of execution.

**Comment by riatzukiza** [comment]
you could change the name to `queue` in the code, make the reference to `stack` a getter, and put a depreciation warning on it, and wait to completely remove it until the next time a major release is justified for other reasons. It would avoid breaking backwards compatibility.

**Comment by dougwilson** [comment]
Yea, but that all seems pointless and I'm not going to make the change. You're welcome to fork the module and publish a version that makes sense to you, of course.  The license if MIT.
