### ISSUE TITLE
Stream based middleware for response modification

### ISSUE THREAD

**Issue by kaysond** [senchalabs/connect#1109]
I've written a middleware that makes it easy to modify responses (particularly from a proxy). I'd love to get official support from the connect/express teams. I'm also happy to make changes. Interested? @dougwilson 

https://github.com/kaysond/http-proxy-interceptor

**Comment by dougwilson** [comment]
Nice module! Happy to help out. What are you looking for? For example what does "[…] get official support […]" mean, exactly?

**Comment by kaysond** [comment]
Thanks! I mostly mean adding it to your readme. Also getting input on changes you think would make it more useful. I'd like to get some more traffic to it so I can actively maintain something that's actually being used.

**Comment by dougwilson** [comment]
So you mean add it to the wiki https://github.com/senchalabs/connect/wiki#contrib-middleware ?

**Comment by kaysond** [comment]
Ah I meant the README.md in the repo, but I now see all of those are actually on the expressjs github account. I just added it to the wiki. Thanks!
