### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [senchalabs/connect#1115]
Hi community!  I am a logo designer. I have reviewed and appreciate your repo.  This repo is quite popular. I think it deserves a logo. Please, are you tell me what you think? Best regards.

![CONNECT](https://user-images.githubusercontent.com/36298335/57183197-12ca6980-6eb2-11e9-803a-5f64f654a48f.jpg)

![connect2](https://user-images.githubusercontent.com/36298335/57183203-1f4ec200-6eb2-11e9-98b0-9871b0cfd059.jpg)

Readme file view;

![connect3](https://user-images.githubusercontent.com/36298335/57183207-24137600-6eb2-11e9-8905-058a0291b354.png)

**Comment by dougwilson** [comment]
Hi @reallinfo thanks for the contribution! I like the logo design and would be happy to incorporate it into the readme as displayed :)

**Comment by reallinfo** [comment]
Of course! I am glad to you like it :D I sent a pr. is there any problem?

https://github.com/senchalabs/connect/pull/1116

**Comment by dougwilson** [comment]
Alright, the PR is merged 🎉
