### ISSUE TITLE
Documentation for "Node.js http request object"

### ISSUE THREAD

**Issue by denilsonsa** [senchalabs/connect#1122]
Short version
--------

Please add links pointing to the proper documentation of `req` and `res` objects.

I don't do it myself (and send the PR) because I'm not familiar with this project and I don't know what is the correct documentation.

Long version
---------

1. Start writing an application using [NuxtJS](https://nuxtjs.org/).
2. Decide you want to write a custom *Server Middleware* in NuxtJS.
3. Find the [official NuxtJS documentation](https://nuxtjs.org/api/configuration-servermiddleware#the-servermiddleware-property). It points to [Connect Docs](https://github.com/senchalabs/connect#appuseroute-fn) (this repository!).
    * I've created [an issue on NuxtJS docs](https://github.com/nuxt/docs/issues/1670) as well.
4. Observe the documentation says:

          // req is the Node.js http request object
          // res is the Node.js http response object

5. Fumble and waste time trying to search the documentation for Node.js http request/response objects.

Expectation: To have a link pointing to the right documentation.

Reality: No link, so now I have to search for it, and hope the documentation I'm reading is the correct one.

**Comment by dougwilson** [comment]
What the objects are exactly will depend on which Nod.je server object you passed connect to. The two lines you quoted above I'm not seeing in my readme here, so not sure where you're getting them from.

**Comment by denilsonsa** [comment]
Sorry, my original link had the wrong `#hash`. Try this: https://github.com/senchalabs/connect#appuseroute-fn

**Comment by dougwilson** [comment]
Right. So the req and res object there are the same ones you passed in to connect originally using https://github.com/senchalabs/connect/blob/master/README.md#appreq-res-next

I can clarify that, but ultimately I don't think that answers your question? What objects did you pass into connect?

**Comment by denilsonsa** [comment]
In my case, I didn't pass any object; instead the NuxtJS framework did it for me.

**Comment by dougwilson** [comment]
Gotcha. So then it would probably need to be clarified by NuxtJS as to what the objects are if that's what you are trying to determine.

**Comment by denilsonsa** [comment]
* [NuxtJS uses `connect` as the app.](https://github.com/nuxt/nuxt.js/blob/a87f5dde6ad5c6a87553ac30e1eb4f462ea7657f/packages/server/src/server.js#L34)
* [NuxtJS uses either `http` or `https` server from Node.js.](https://github.com/nuxt/nuxt.js/blob/a87f5dde6ad5c6a87553ac30e1eb4f462ea7657f/packages/server/src/listener.js#L65)
* [NuxtJS passes the `connect` app as the `requestListener` parameter of `createServer`.](https://github.com/nuxt/nuxt.js/blob/a87f5dde6ad5c6a87553ac30e1eb4f462ea7657f/packages/server/src/listener.js#L67)
* There doesn't seem to be any option `IncomingMessage` or `ServerResponse` in [connect](https://github.com/senchalabs/connect/blob/bd0d23d/index.js), in [NuxtJS listener](https://github.com/nuxt/nuxt.js/blob/a87f5dde6ad5c6a87553ac30e1eb4f462ea7657f/packages/server/src/listener.js), or in [NuxtJS server](https://github.com/nuxt/nuxt.js/blob/a87f5dde6ad5c6a87553ac30e1eb4f462ea7657f/packages/server/src/server.js); thus I believe the `req` and `res` will be the ones defined/documented at [http.createServer](https://nodejs.org/api/http.html#http_http_createserver_options_requestlistener):
    * [`http.IncomingMessage`](https://nodejs.org/api/http.html#http_class_http_incomingmessage)
    * [`http.ServerResponse`](https://nodejs.org/api/http.html#http_class_http_serverresponse)

So… There is no explicit request object being passed to `connect`, as suggested in https://github.com/senchalabs/connect/issues/1122#issuecomment-544958370 . Instead, it is just Node.js passing its own default objects.

(Note: I'm not complaining, I'm just taking note of my findings.)

**Comment by dougwilson** [comment]
> NuxtJS passes the connect app as the requestListener parameter of createServer.

So that is the part where NuxtJS is chosing what the req and res are going to be, by passing connect to that method. If it passed connect to something in the http2 node js module, for instance, than it would be the http2 objects coming though in connect. I hope that makes sense what I mean by the objects are whatever was passes into connect, and not something connect would have set in stone such that could be documented here like you're seeking.
