### ISSUE TITLE
Drop unsupported Node.js version

### ISSUE THREAD

**Issue by artursvonda** [senchalabs/connect#1124]
Any plans to release a new major version that drop unsupported node.js versions in order to allow updating the dependencies to newer versions and allowing to use newer features? Would also allow to clean up the code a bit.

**Comment by dougwilson** [comment]
Hello! There are no current plans as of now. If there are specific version of Node.js that are a minimum requirement for some feature, then that is possible of course.

If you have some things in mind, please feel free to open up a new issue for each individual change / feature request you are thinking of so they can be individually discussed, tracked, and potentially implemented :+1:
