### ISSUE TITLE
whether can we give up nodejs that is less than version 7 ?

### ISSUE THREAD

**Issue by anlexN** [senchalabs/connect#1126]

**Comment by dougwilson** [comment]
No

**Comment by anlexN** [comment]
why?

**Comment by dougwilson** [comment]
Because this module is very simple in order to work across as many Node.js versions as possible.

**Comment by anlexN** [comment]
i am very angry, why support very old nodejs version. i review your source code that is to be not let me  good understand.

**Comment by dougwilson** [comment]
I mean, this module is published my people with a specific goal in mind. This is the goal of this project. You're always welcome to publish a module that provides the support you are looking for to npm 👍
