### ISSUE TITLE
release

### ISSUE THREAD

**Issue by PachVerb** [senchalabs/connect#1130]
Why not attach the changelog when the version is iterated？:(

**Comment by dougwilson** [comment]
Hi @PachVerb I'm not sure what you mean. We do include a change log for every release both in the repo (https://github.com/senchalabs/connect/blob/master/HISTORY.md) and also include that inside of the npm package as well.

**Comment by PachVerb** [comment]
> Hi @PachVerb I'm not sure what you mean. We do include a change log for every release both in the repo (https://github.com/senchalabs/connect/blob/master/HISTORY.md) and also include that inside of the npm package as well.

fine
