### ISSUE TITLE
Content-Type: 'application/fhir+json'

### ISSUE THREAD

**Issue by awatson1978** [senchalabs/connect#1133]
Hello,
Can you recommend any approaches or workarounds for getting custom content types working?  

I'm working on some healthcare apps using the ANSI accredited [FHIR standard](https://www.hl7.org/fhir/index.html), which defines a constrained flavor of JSON, using the `application/fhir+json` content type.  

I've been running some software that utilizes this `connect` library through federal testing services over at [https://inferno.healthit.gov/](https://inferno.healthit.gov/) and [https://touchstone.aegis.net/](https://touchstone.aegis.net/), and they're kicking errors on the content-type.  

After replicating the issue on my laptop with Postman, it appears that when a `PUT` request is sent with a `application/fhir+json` Content-Type header, the `req.body` field returns with an empty `{}` object.  

When we PUT with a typical `application/json` header, the `req.body` includes the expected data payload.

Scanning through the Issues log, it appears it might be related to #354?  

Is there any workaround that we can use to tell `connect` that `application/fhir+json` is allowable and effectively the same as `application/json`?  Maybe a config setting?  Or middleware solutions?

**Comment by dougwilson** [comment]
Hi, sorry you are having trouble. The only supported version of connect does not have any kind of req.body or similar. You would need to be using some kind of module to read the request and there are a lot out there. You'll want to open this issue on whatever module you are using to reqd the request. If you are actually using an unsupported version of connect (less than 3.x) you really should upgrade 😀

**Comment by awatson1978** [comment]
Not only were you correct that it was the other module that was responsible for the error, but I found a pull request from 2017 that I submitted on it fixing the issue that never got accepted or merged in!  D'oh!  lmao...

Thanks for the quick and clear response!
