### ISSUE TITLE
bug: redirecting to external URLs

### ISSUE THREAD

**Issue by benmccann** [senchalabs/connect#1137]
### Steps to reproduce

```
git clone https://github.com/benmccann/connect-repro
cd connect-repro
npm install
node index.js
```

Visit http://localhost:3000//www.google.com/ and you will be incorrectly redirected to google.com.

### Security implications

This is arguable a security bug https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html

The [security policy](https://github.com/senchalabs/connect/security/policy) asks to email the lead maintainer, but that email address is not obviously published. This didn't seem like a sever enough issue that I'd try to track down an email, but I thought I'd point this out in case it helps future security issues be reported correctly

**Comment by dougwilson** [comment]
Hello @benmccann thanks for the report. There is no code in `connect` that does any kind of redirection, so it is unclear what your issue is. In fact, following your steps, it properly responds with a 200 with your response, no redirect or `Location` response header:
```
$ git clone https://github.com/benmccann/connect-repro connect-1137
Cloning into 'connect-1137'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 6 (delta 0), pack-reused 0
Receiving objects: 100% (6/6), done.
$ cd connect-1137/
$ npm i

added 12 packages, and audited 13 packages in 938ms

found 0 vulnerabilities
$ node index.js &
[1] 2894
$ curl -i http://localhost:3000//www.google.com/
HTTP/1.1 200 OK
Date: Mon, 21 Mar 2022 16:39:11 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Length: 20

Hello from Connect!
```

In the future, please respect our security policy.

**Comment by benmccann** [comment]
Perhaps an OS or version issue. I'm definitely seeing a redirect in Chrome 98 for Linux. In any case, it seems unlikely to be an issue in Connect

I'm afraid even logged in I do not see your email address in your profile. You may want to note the `npm owner ls` or `package.json` tips in the security policy to help people locate your email if needed. Here's a screenshot of what I see

![Screenshot from 2022-03-21 09-59-41](https://user-images.githubusercontent.com/322311/159325276-e6904054-16bc-4636-ab45-fb86898b1754.png)
