### ISSUE TITLE
static is reserved word in JS

### ISSUE THREAD

**Issue by wavded** [senchalabs/connect#229]
JSLint isn't passing because staticProvider was renamed to static and static is a reserved word in JS.  Can we get an alias or a rename?

**Comment by attaab** [comment]
usually before writing my codes i gave jsLint some hints on commands to pass..
for example when i code in Nodejs..
i put this on top of my code..
/*jslint node: true*/
and when i want to use Es6 i tell jslint - 
/*jslint es6: true*/
this way i get no errors when i use characters peculiar to those scope

**Comment by dcsan** [comment]
5 years later... the typescript linter also complains about this, and seems harder to disable.
