### ISSUE TITLE
Option to not send cookies on certain HTTP method request (e.g. OPTIONS)

### ISSUE THREAD

**Issue by ghost** [senchalabs/connect#323]
Hello - 

I've recently noticed that certain (all?) browsers do not send cookies with OPTIONS requests, but session (understandably) sends a cookie response with a new session ID in response to these. (OPTIONS requests are used to probe CORS access control headers prior to sending AJAX requests.) 

My specific scenario is the following:
1. request http://m.tixelated.com
   1a. Receive cookie with new session ID
2. AJAX OPTIONS request to http://api.tixelated.com to probe for CORS headers (this is automatically generated by the browser)
   2a. Browser does not send cookie
   2b. Session responds with Set-Cookie header and NEW session ID
3. Subsequent requests to http://api.tixelated.com use different session ID

I've confirmed that GET requests to various subdomains work correctly with my setup.

Proposed solution: an option to allow disabling sessions/cookie responses for certain HTTP requests, in this case OPTIONS (there may be other use cases. If not, a simple boolean for that method would suffice.)

(Or - maybe I'm doing something boneheaded.)

**Comment by azherf** [comment]
Hi,

I know this is an old thread, but, were you guys able to find a fix for the above mentioned use case ? I am facing the exact issue and I am not finding any help anywhere.

Any kind of lead will be great. Thanks in advance.

**Comment by bgSosh** [comment]
I second azherf - is there a proper way to do this yet?

**Comment by dougwilson** [comment]
The current version of `connect` has no session code or anything for us to change to address any problem with it. I assume you are using a discontinued version of connect, which is not a supported line.
